// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Capacity.proto
// Protobuf Java Version: 4.28.3

package com.protos;

public interface CapacityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dist_servers.Capacity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 server_id = 1;</code>
   * @return The serverId.
   */
  int getServerId();

  /**
   * <code>int32 serverX_status = 2;</code>
   * @return The serverXStatus.
   */
  int getServerXStatus();

  /**
   * <code>int64 timestamp = 3;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
