// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Configuration.proto
// Protobuf Java Version: 4.28.3

package com.protos;

public interface ConfigurationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dist_servers.Configuration)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 fault_tolerance_level = 1;</code>
   * @return The faultToleranceLevel.
   */
  int getFaultToleranceLevel();

  /**
   * <code>.dist_servers.MethodType method_type = 2;</code>
   * @return The enum numeric value on the wire for methodType.
   */
  int getMethodTypeValue();
  /**
   * <code>.dist_servers.MethodType method_type = 2;</code>
   * @return The methodType.
   */
  com.protos.MethodType getMethodType();
}
