// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Configuration.proto
// Protobuf Java Version: 4.28.3

package com.protos;

public final class ConfigurationJava {
  private ConfigurationJava() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      ConfigurationJava.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dist_servers_Configuration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dist_servers_Configuration_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023Configuration.proto\022\014dist_servers\"]\n\rC" +
      "onfiguration\022\035\n\025fault_tolerance_level\030\001 " +
      "\001(\005\022-\n\013method_type\030\002 \001(\0162\030.dist_servers." +
      "MethodType* \n\nMethodType\022\010\n\004STRT\020\000\022\010\n\004ST" +
      "OP\020\001B!\n\ncom.protosB\021ConfigurationJavaP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dist_servers_Configuration_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dist_servers_Configuration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dist_servers_Configuration_descriptor,
        new java.lang.String[] { "FaultToleranceLevel", "MethodType", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
