// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dist_servers/Message.proto
// Protobuf Java Version: 4.28.3

package com.protos;

/**
 * Protobuf type {@code dist_servers.Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:dist_servers.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      Message.class.getName());
  }
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    demand_ = 0;
    response_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.protos.MessageJava.internal_static_dist_servers_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.protos.MessageJava.internal_static_dist_servers_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.protos.Message.class, com.protos.Message.Builder.class);
  }

  public static final int DEMAND_FIELD_NUMBER = 1;
  private int demand_ = 0;
  /**
   * <code>.dist_servers.Demand demand = 1;</code>
   * @return The enum numeric value on the wire for demand.
   */
  @java.lang.Override public int getDemandValue() {
    return demand_;
  }
  /**
   * <code>.dist_servers.Demand demand = 1;</code>
   * @return The demand.
   */
  @java.lang.Override public com.protos.Demand getDemand() {
    com.protos.Demand result = com.protos.Demand.forNumber(demand_);
    return result == null ? com.protos.Demand.UNRECOGNIZED : result;
  }

  public static final int RESPONSE_FIELD_NUMBER = 2;
  private int response_ = 0;
  /**
   * <code>.dist_servers.Response response = 2;</code>
   * @return The enum numeric value on the wire for response.
   */
  @java.lang.Override public int getResponseValue() {
    return response_;
  }
  /**
   * <code>.dist_servers.Response response = 2;</code>
   * @return The response.
   */
  @java.lang.Override public com.protos.Response getResponse() {
    com.protos.Response result = com.protos.Response.forNumber(response_);
    return result == null ? com.protos.Response.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (demand_ != com.protos.Demand.CPCTY.getNumber()) {
      output.writeEnum(1, demand_);
    }
    if (response_ != com.protos.Response.YEP.getNumber()) {
      output.writeEnum(2, response_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (demand_ != com.protos.Demand.CPCTY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, demand_);
    }
    if (response_ != com.protos.Response.YEP.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, response_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.protos.Message)) {
      return super.equals(obj);
    }
    com.protos.Message other = (com.protos.Message) obj;

    if (demand_ != other.demand_) return false;
    if (response_ != other.response_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DEMAND_FIELD_NUMBER;
    hash = (53 * hash) + demand_;
    hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
    hash = (53 * hash) + response_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.protos.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.protos.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.protos.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.protos.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.protos.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.protos.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.protos.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.protos.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.protos.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.protos.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.protos.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.protos.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.protos.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dist_servers.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dist_servers.Message)
      com.protos.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.MessageJava.internal_static_dist_servers_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.MessageJava.internal_static_dist_servers_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.Message.class, com.protos.Message.Builder.class);
    }

    // Construct using com.protos.Message.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      demand_ = 0;
      response_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.protos.MessageJava.internal_static_dist_servers_Message_descriptor;
    }

    @java.lang.Override
    public com.protos.Message getDefaultInstanceForType() {
      return com.protos.Message.getDefaultInstance();
    }

    @java.lang.Override
    public com.protos.Message build() {
      com.protos.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.protos.Message buildPartial() {
      com.protos.Message result = new com.protos.Message(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.protos.Message result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.demand_ = demand_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.response_ = response_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.protos.Message) {
        return mergeFrom((com.protos.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.protos.Message other) {
      if (other == com.protos.Message.getDefaultInstance()) return this;
      if (other.demand_ != 0) {
        setDemandValue(other.getDemandValue());
      }
      if (other.response_ != 0) {
        setResponseValue(other.getResponseValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              demand_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              response_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int demand_ = 0;
    /**
     * <code>.dist_servers.Demand demand = 1;</code>
     * @return The enum numeric value on the wire for demand.
     */
    @java.lang.Override public int getDemandValue() {
      return demand_;
    }
    /**
     * <code>.dist_servers.Demand demand = 1;</code>
     * @param value The enum numeric value on the wire for demand to set.
     * @return This builder for chaining.
     */
    public Builder setDemandValue(int value) {
      demand_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.dist_servers.Demand demand = 1;</code>
     * @return The demand.
     */
    @java.lang.Override
    public com.protos.Demand getDemand() {
      com.protos.Demand result = com.protos.Demand.forNumber(demand_);
      return result == null ? com.protos.Demand.UNRECOGNIZED : result;
    }
    /**
     * <code>.dist_servers.Demand demand = 1;</code>
     * @param value The demand to set.
     * @return This builder for chaining.
     */
    public Builder setDemand(com.protos.Demand value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      demand_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.dist_servers.Demand demand = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDemand() {
      bitField0_ = (bitField0_ & ~0x00000001);
      demand_ = 0;
      onChanged();
      return this;
    }

    private int response_ = 0;
    /**
     * <code>.dist_servers.Response response = 2;</code>
     * @return The enum numeric value on the wire for response.
     */
    @java.lang.Override public int getResponseValue() {
      return response_;
    }
    /**
     * <code>.dist_servers.Response response = 2;</code>
     * @param value The enum numeric value on the wire for response to set.
     * @return This builder for chaining.
     */
    public Builder setResponseValue(int value) {
      response_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.dist_servers.Response response = 2;</code>
     * @return The response.
     */
    @java.lang.Override
    public com.protos.Response getResponse() {
      com.protos.Response result = com.protos.Response.forNumber(response_);
      return result == null ? com.protos.Response.UNRECOGNIZED : result;
    }
    /**
     * <code>.dist_servers.Response response = 2;</code>
     * @param value The response to set.
     * @return This builder for chaining.
     */
    public Builder setResponse(com.protos.Response value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      response_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.dist_servers.Response response = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearResponse() {
      bitField0_ = (bitField0_ & ~0x00000002);
      response_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:dist_servers.Message)
  }

  // @@protoc_insertion_point(class_scope:dist_servers.Message)
  private static final com.protos.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.protos.Message();
  }

  public static com.protos.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.protos.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

