// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dist_servers/Message.proto
// Protobuf Java Version: 4.28.3

package com.protos;

public final class MessageJava {
  private MessageJava() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      MessageJava.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dist_servers_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dist_servers_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032dist_servers/Message.proto\022\014dist_serve" +
      "rs\"Y\n\007Message\022$\n\006demand\030\001 \001(\0162\024.dist_ser" +
      "vers.Demand\022(\n\010response\030\002 \001(\0162\026.dist_ser" +
      "vers.Response*\035\n\006Demand\022\t\n\005CPCTY\020\000\022\010\n\004ST" +
      "RT\020\001*\034\n\010Response\022\007\n\003YEP\020\000\022\007\n\003NOP\020\001B\033\n\nco" +
      "m.protosB\013MessageJavaP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dist_servers_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dist_servers_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dist_servers_Message_descriptor,
        new java.lang.String[] { "Demand", "Response", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
