// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dist_servers/Message.proto
// Protobuf Java Version: 4.28.3

package com.protos;

/**
 * Protobuf enum {@code dist_servers.Response}
 */
public enum Response
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>YEP = 0;</code>
   */
  YEP(0),
  /**
   * <code>NOP = 1;</code>
   */
  NOP(1),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      Response.class.getName());
  }
  /**
   * <code>YEP = 0;</code>
   */
  public static final int YEP_VALUE = 0;
  /**
   * <code>NOP = 1;</code>
   */
  public static final int NOP_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Response valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Response forNumber(int value) {
    switch (value) {
      case 0: return YEP;
      case 1: return NOP;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Response>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Response> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Response>() {
          public Response findValueByNumber(int number) {
            return Response.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.protos.MessageJava.getDescriptor().getEnumTypes().get(1);
  }

  private static final Response[] VALUES = values();

  public static Response valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Response(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:dist_servers.Response)
}

