// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dist_servers/Subscriber.proto
// Protobuf Java Version: 4.28.3

package com.protos;

public interface SubscriberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dist_servers.Subscriber)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name_surname = 1;</code>
   * @return The nameSurname.
   */
  java.lang.String getNameSurname();
  /**
   * <code>string name_surname = 1;</code>
   * @return The bytes for nameSurname.
   */
  com.google.protobuf.ByteString
      getNameSurnameBytes();

  /**
   * <code>int64 start_Date = 2;</code>
   * @return The startDate.
   */
  long getStartDate();

  /**
   * <code>int64 last_accessed = 3;</code>
   * @return The lastAccessed.
   */
  long getLastAccessed();

  /**
   * <code>repeated string interests = 5;</code>
   * @return A list containing the interests.
   */
  java.util.List<java.lang.String>
      getInterestsList();
  /**
   * <code>repeated string interests = 5;</code>
   * @return The count of interests.
   */
  int getInterestsCount();
  /**
   * <code>repeated string interests = 5;</code>
   * @param index The index of the element to return.
   * @return The interests at the given index.
   */
  java.lang.String getInterests(int index);
  /**
   * <code>repeated string interests = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the interests at the given index.
   */
  com.google.protobuf.ByteString
      getInterestsBytes(int index);

  /**
   * <code>bool isOnline = 6;</code>
   * @return The isOnline.
   */
  boolean getIsOnline();

  /**
   * <code>.dist_servers.DemandType demand = 7;</code>
   * @return The enum numeric value on the wire for demand.
   */
  int getDemandValue();
  /**
   * <code>.dist_servers.DemandType demand = 7;</code>
   * @return The demand.
   */
  com.protos.DemandType getDemand();

  /**
   * <code>int64 ID = 8;</code>
   * @return The iD.
   */
  long getID();
}
